// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  scriptSidebar: [{ type: 'autogenerated', dirName: 'crbtscript' }],
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
  selfHostingSidebar: [{ type: 'autogenerated', dirName: 'self-hosting' }],
};

module.exports = sidebars;
